spring:

#  security:
#    user:
#      name: admin
#      password: 1234

#  datasource:
#    url: jdbc:mysql://localhost:3306/hotel
#    username: root
#    password: viethoan2k1

  datasource:
    url: mysql://root:DDqiHRSHz1BsfH799soZ@containers-us-west-48.railway.app:5728/railway
    username: root
    password: DDqiHRSHz1BsfH799soZDDqiHRSHz1BsfH799soZ

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

   